name = "well-known"
type = "webpack"
# *.m4rc3l.de
routes = [
    "*m4rc3l.de/robots.txt",
    "*m4rc3l.de/.well-known/*"
]
zone_id = "b820a9fe742f410d3dfb40cc398c7577"
account_id = "2a09613716e511a8fe8ca74abc084762"
workers_dev = false
